name: 'Setup MongoDB and Redis'
description: 'Sets up MongoDB and Redis for testing'

inputs:
  mongodb-version:
    description: 'MongoDB version to use'
    required: false
    default: '4.4'
  redis-version:
    description: 'Redis version to use'
    required: false
    default: '6'

runs:
  using: 'composite'
  steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: ${{ inputs.mongodb-version }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.8.0
      with:
        redis-version: ${{ inputs.redis-version }}
